version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: review
      POSTGRES_PASSWORD: postgres_password

  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"
